server:
  port: 8082

spring:
  application:
    name: coffique-auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - org.springframework.web.client.RestClientException

  ratelimiter:
    instances:
      loginLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1m
        timeoutDuration: 0

  bulkhead:
    instances:
      userService:
        maxConcurrentCalls: 10
        maxWaitDuration: 1s

  timelimiter:
    instances:
      userService:
        timeoutDuration: 2s
        cancelRunningFuture: true
