server:
  port: 8082

spring:
  application:
    name: coffique-auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

  endpoint:
    health:
      show-details: always
