spring:
  application:
    name: coffique-api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true
